language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_base;'
  - mysql -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'admin'@'localhost';"
  - mysql -e 'FLUSH PRIVILEGES;'
install:
- mvn clean install
