language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_base;'
  - mysql -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'admin'@'localhost';"
  - mysql -e 'FLUSH PRIVILEGES;'
  - chmod +x mvnw
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
