server:
  port: 8085

spring:
# ===============================
# = DATA SOURCE
# ===============================

  # Set here configurations for the database connection
  datasource:
    # Connection url for the database "test_base"
    url: jdbc:mysql://localhost:3306/test_base?useUnicode=yes&characterEncoding=UTF-8

    # Username and password
    username: admin
    password: admin

    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================

  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager).
  jpa:
    # Show or not log for each sql query
    show-sql: true

    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: update

      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect